apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: mariadb
type: Opaque
data:
  mysql-root-password: YWRtaW4=  # base64 for "admin"
  mysql-password: cGFzc3dvcmQ=  # base64 for "password"
